version: "3.7"

services:
  gomic:
    image: gomic
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongodb
      - rabbitmq
    restart: on-failure
    networks:
      - gomic-network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "gomic-data:/data/db"
    networks:
      - gomic-network

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - gomic-network

  e2e_test:
    image: python:buster
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./e2e_test.sh
        target: /e2e_test.sh
    command: ["/bin/bash", "/e2e_test.sh"]
    networks:
      - gomic-network

volumes:
  gomic-data:

networks:
  gomic-network:
