version: "3"

services:
  gomic:
    image: gomic
    ports:
      - "8080:8080"
    environment:
      - MONGODB_HOST=mongodb://mongodb:27017
      - MONGODB_DATABASE=db
      - MONGODB_COLLECTION=persons
      - RABBITMQ_HOST=amqp://guest:guest@rabbitmq:5672
      - RABBITMQ_SOURCE_EXCHANGE=source-exchange
      - RABBITMQ_SOURCE_QUEUE=source-queue
      - RABBITMQ_SOURCE_ROUTING_KEY=source-routing-key
      - RABBITMQ_CONSUMER_TAG=simple-consumer
      - RABBITMQ_DESTINATION_EXCHANGE=destination-exchange
      - RABBITMQ_DESTINATION_ROUTING_KEY=destination-routing-key
    depends_on:
      - mongodb
      - rabbitmq
    restart: on-failure
    networks:
      - gomic-network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "gomic-data:/data/db"
    networks:
      - gomic-network

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - gomic-network

volumes:
  gomic-data:

networks:
  gomic-network:
